AWSTemplateFormatVersion: '2010-09-09'
Description: Creates a secure S3 bucket with public access blocked and encryption enabled.

Resources:
  SecureBucket:
    Type: AWS::S3::Bucket
    Properties:
      # Note: S3 bucket names must be globally unique. 
      # You may need to change this bucket name to deploy the stack successfully.
      BucketName: my-secure-bucket-for-grc-book
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
